### ISSUE TITLE
`NvimError: end_row value outside range` when running `MakeComment`

### ISSUE THREAD

**Issue by oxytocin** [oxytocin/DocComments#4]
from @fernandoalex:

> Thanks for the response @oxytocin , I added `pip3 install neovim` and ran `UpdateRemotePlugind` and this problem went away, but as soon as I tried to create a comment with `MakeComment` I got another error.
> 
> ```
> error caught in async handler '/Users/USER/.local/share/nvim/plugged/DocComments/rplugin/python3/DocComments.py:command:MakeComment [[39, 39]]'
> Traceback (most recent call last):
>   File "/Users/USER/.local/share/nvim/plugged/DocComments/rplugin/python3/DocComments.py", line 91, in make_comment
>     self.nvim.api.buf_set_extmark(0, self.ns, start_row, start_col, options)
>   File "/usr/local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
>     res = self._session.request(name, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
>     raise self.error_wrapper(err)
> pynvim.api.common.NvimError: end_row value outside range
> ```
> 
> Tested with strings:
> 
> `test`
> `test comment`
> 
> Since it is not related to the initial problem, shall I make another issue?
> 
> Again thanks for the help 🙇
>

**Comment by oxytocin** [comment]
@fernandoalex Were you in normal mode or visual mode when you ran `MakeComment`? If visual mode, what part of the text was highlighted?

**Comment by fernandoalex** [comment]
🤦 I am sorry, was in normal mode, I should have paid more attention to the README.md. 

This can be closed, tested stuff and it is all working.

Thanks for your time!

**Comment by oxytocin** [comment]
No problem, I hope you find the plugin helpful. I'll probably add a warning to the user if they use `MakeComment` in normal mode because I don't want anyone else getting tripped up.
