### ISSUE TITLE
Feature Request: Custom storage location

### ISSUE THREAD

**Issue by dlford** [oxytocin/DocComments#5]
Hi,

Cool idea and thanks for sharing!

It would be great to have a config option to store the comments files somewhere else (e.g. `~/.local/share/DocComments/FILE_PATH/FILE_NAME_notes.txt`), that way they won't wind up in git repositories by accident.

**Comment by oxytocin** [comment]
Sorry for taking forever to reply to this. I've been thinking about how I would implement this but am not sure of the best way to link comment files to their respective text files. If we base it just on the filename, then it will cause problems if the user has 2 files with the same name in different directories. On the other hand, if we base it off the full path, then renaming any directory along that path will break the connection, which strikes me as undesirable—or maybe people don't mind that as much as I think they do. Would be interested to hear opinions.

**Comment by oxytocin** [comment]
I added this feature in commit [c76ec76](https://github.com/oxytocin/DocComments/commit/c76ec767de4e738726966b6865d1ac0179f621fa). I opted to base the custom comment file path off the full path of the original file, so it will break if directories are renamed. Comment files are still stored in the same directory as the original file by default.
